const filters = [
  {
    id: "GroupId_autofill_multi",
    type: "autofill",
    label: "DallasId",
    multi: true,
    result: {
      apiFunction: "licenses.getGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "GroupId",
      value: "GroupId",
    },
  },
  {
    id: "SerialNumber_autofill_multi",
    type: "autofill",
    label: "SerialNumber",
    multi: true,
    result: {
      apiFunction: "licenses.getGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "SerialNumber",
      value: "SerialNumber",
    },
  },
  {
    id: "AppTitle_autofill_multi",
    type: "autofill",
    label: "AppTitle",
    multi: true,
    result: {
      apiFunction: "licenses.getGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "AppTitle",
      value: "AppTitle",
    },
  },
  {
    id: "IP_autofill_multi",
    type: "autofill",
    label: "IP",
    multi: true,
    result: {
      apiFunction: "licenses.getGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "IP",
      value: "IP",
    },
  },
  {
    id: "LastDate_date_range",
    type: "date_range",
    label: "LastDate",
    multi: true,
    result: {
      apiFunction: "licenses.getGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "LastDate",
      value: "LastDate",
    },
  },
  {
    id: "LastPingTimeStamp_date_range",
    type: "date_range",
    label: "LastPingTimeStamp",
    multi: true,
    result: {
      apiFunction: "licenses.getGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "LastPingTimeStamp",
      value: "LastPingTimeStamp",
    },
  },
];
export default filters;
