
const table = {
  token: "SEARCH_TABLE",
  paginationRowsPerPageOptions: [25],
  paginationRowsPerPage: 25,
  onlyFilteredQueries: true,
  rowTitle: "Id",
  result: {
    apiFunction: "search.searchDevices"
  },
  sort: { column: "Id", direction: "asc" },

  customHeadStyles: {
    Active: { justifyContent: "center" },
    validated: { justifyContent: "center" },
    WhyActive: { justifyContent: "flex-end" },
    ActionRequest: { justifyContent: "center" },
  },
  columns: [
    {
      name: "",
      key: "actions",
      width: "50px",
      reorder: true,
    },
    {
      name: "Id",
      key: "Id",
      selector: true,
      sortable: true,
      width: "350px",
      reorder: true,
    },
    {
      name: "GroupId",
      key: "GroupId",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "SerialNumber",
      key: "SerialNumber",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "MachineId",
      key: "MachineId",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "Active",
      key: "Active",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
      style: { justifyContent: "center" },
    },
    {
      name: "ManufacturerSerialNumber",
      key: "ManufacturerSerialNumber",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "Type",
      key: "Type",
      selector: true,
      sortable: true,
      reorder: true,
      width: "180px",
    },
    {
      name: "TypeInfo",
      key: "TypeInfo",
      selector: true,
      sortable: true,
      reorder: true,
      width: "300px",
    },
    {
      name: "LastPingTimeStamp",
      key: "LastPingTimeStamp",
      selector: true,
      sortable: true,
      reorder: true,
      width: "180px",
    },
    {
      name: "LastLifeDate",
      key: "LastLifeDate",
      selector: true,
      sortable: true,
      reorder: true,
      width: "180px",
    },
    {
      name: "RPI",
      key: "RPI",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "SpareOrder",
      key: "SpareOrder",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "ClientNumber",
      key: "ClientNumber",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "OfflineActived",
      key: "OfflineActived",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "OfflineActivedDate",
      key: "OfflineActivedDate",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "OfflineActivedKey",
      key: "OfflineActivedKey",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "OfflineActiveRequest",
      key: "OfflineActiveRequest",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "LastActivatedDate",
      key: "LastActivatedDate",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "IdLastActivatedDate",
      key: "IdLastActivatedDate",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "FirstDate",
      key: "FirstDate",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "LastMachineDate",
      key: "LastMachineDate",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "LastIP",
      key: "LastIP",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "MachineSerialNumber",
      key: "MachineSerialNumber",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "ProductDefinition",
      key: "ProductDefinition",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "LastDate",
      key: "LastDate",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
  ],
};

export default table;
