
const table = {
  token: "FACTORY_SEARCH_TABLE",
  paginationRowsPerPageOptions: [25, 50, 100, 200],
  paginationRowsPerPage: 25,
  rowTitle: "Id",
  fixedHeight: true,
  onlyFilteredQueries: true,
  result: {
    apiFunction: "search.searchFactoryDevices"
  },
  sort: { column: "Id", direction: "asc" },

  customHeadStyles: {
    Active: { justifyContent: "center" },
    validated: { justifyContent: "center" },
    WhyActive: { justifyContent: "flex-end" },
    ActionRequest: { justifyContent: "center" },
  },
  columns: [
    {
      name: "",
      key: "actions",
      width: "125px",
      reorder: true,
    },
    {
      name: "Id",
      key: "Id",
      selector: true,
      sortable: true,
      width: "350px",
      reorder: true,
    },
    {
      name: "SerialNumber",
      key: "SerialNumber",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "MachineId",
      key: "MachineId",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "FactoryMachineSerialNumber",
      key: "FactoryMachineSerialNumber",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "validated",
      key: "validated",
      selector: true,
      sortable: true,
      reorder: true,
      width: "120px",
      style: { justifyContent: "center" },
    },
    {
      name: "FactoryDispatchedDate",
      key: "FactoryDispatchedDate",
      selector: true,
      sortable: true,
      width: "150px",
      reorder: true,
    },
    {
      name: "request",
      key: "ActionRequest",
      selector: true,
      sortable: true,
      reorder: true,
      width: "120px",
      style: { justifyContent: "center" },
    },
    {
      name: "ManufacturerSerialNumber",
      key: "ManufacturerSerialNumber",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
    {
      name: "Type",
      key: "Type",
      selector: true,
      sortable: true,
      reorder: true,
      width: "180px",
    },
    {
      name: "TypeInfo",
      key: "TypeInfo",
      selector: true,
      sortable: true,
      reorder: true,
      width: "300px",
    },
    {
      name: "LastPingTimeStamp",
      key: "LastPingTimeStamp",
      selector: true,
      sortable: true,
      reorder: true,
      width: "180px",
    },
    {
      name: "RPI",
      key: "RPI",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "ProductDefinition",
      key: "ProductDefinition",
      selector: true,
      sortable: true,
      reorder: true,
      width: "200px",
    },
    {
      name: "Active",
      key: "Active",
      selector: true,
      sortable: true,
      reorder: true,
      width: "100px",
      style: { justifyContent: "center" },
    },
    {
      name: "SpareOrder",
      key: "SpareOrder",
      selector: true,
      sortable: true,
      reorder: true,
      width: "150px",
    },
    {
      name: "ClientName",
      key: "ClientName",
      selector: true,
      sortable: true,
      reorder: true,
      width: "150px",
    },
    {
      name: "ClientNumber",
      key: "ClientNumber",
      selector: true,
      sortable: true,
      reorder: true,
      width: "150px",
    },
    {
      name: "MachineSerialNumber",
      key: "MachineSerialNumber",
      selector: true,
      sortable: true,
      width: "200px",
      reorder: true,
    },
  ],
};

export default table;
