const filters = [
  {
    id: "FactoryDispatched_select",
    type: "select",
    label: "dispatched",
    options: [
      { value: 1, label: "yes" },
      { value: 0, label: "no" },
    ],
  },
  {
    id: "SerialNumber_autofill_multi",
    type: "autofill",
    label: "SerialNumber",
    multi: true,
    result: {
      apiFunction: "factory.getFactoryGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "SerialNumber",
      value: "SerialNumber",
    },
  },
  {
    id: "FactoryMachineSerialNumber_autofill",
    type: "autofill",
    label: "FactoryMachineSerialNumber",
    multi: false,
    result: {
      apiFunction: "filters.getFactoryFilterFactoryMachineSerialNumbers",
      data: "result",
      success: "success",
      message: "message",
      label: "FactoryMachineSerialNumber",
      value: "FactoryMachineSerialNumber",
    },
  },
  {
    id: "GroupId_autofill_multi",
    type: "autofill",
    label: "DallasId",
    multi: true,
    result: {
      apiFunction: "factory.getFactoryGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "GroupId",
      value: "GroupId",
    },
  },
  {
    id: "AppTitle_autofill_multi",
    type: "autofill",
    label: "AppTitle",
    multi: true,
    result: {
      apiFunction: "factory.getFactoryGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "AppTitle",
      value: "AppTitle",
    },
  },
  {
    id: "LastDate_date_range",
    type: "date_range",
    label: "LastDate",
    multi: true,
    result: {
      apiFunction: "factory.getFactoryGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "LastDate",
      value: "LastDate",
    },
  },
  {
    id: "LastPingTimeStamp_date_range",
    type: "date_range",
    label: "LastPingTimeStamp",
    multi: true,
    result: {
      apiFunction: "factory.getFactoryGroupsAll",
      data: "result",
      success: "success",
      message: "message",
      label: "LastPingTimeStamp",
      value: "LastPingTimeStamp",
    },
  },
];
export default filters;
